// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv

import { defineConfig } from 'prisma/config';
import dotenv from 'dotenv';
dotenv.config();

const getDatabaseUrl = () => {
  if (process.env['NODE_ENV'] === 'test') {
    return process.env['TEST_DB_URI'] || '';
  }
  return process.env['DATABASE_URL'] || '';
};

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: getDatabaseUrl(),
  },
});
